# application.yml
server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: mcp-client
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update   # (use 'validate' in production)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mcp:
  client:
    name: ${MCP_CLIENT_NAME}
    version: ${MCP_CLIENT_VERSION}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

logging:
  level:
    com.mcp.client: DEBUG
    root: INFO
  
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always


---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.mcp.client: TRACE

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.mcp.client: INFO
