# application.yml
server:
  port: 8080

spring:
  application:
    name: mcp-client
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=mcp_client;encrypt=false
    username: sa
    password: root@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update   # (use 'validate' in production)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mcp:
  client:
    name: "spring-mcp-client"
    version: "1.0.0"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

logging:
  level:
    com.example.mcpclient: DEBUG
    root: INFO
  
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always


---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.example.mcpclient: TRACE

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.example.mcpclient: INFO